### ISSUE TITLE
Add the filessss!

### ISSUE THREAD

**Issue by joshmn** [djzk/serverroom#2]
This looks so pretty. I want to see it under the hood. :( :) <3

**Comment by djzk** [comment]
Thanks. Soon. Right now I'm making things smoother and look better :)

**Comment by Kjarrigan** [comment]
Any chance we might see this soon - it looks amazing :+1: Did you make alle the graphics yourself? 

I'm especially interessted in your isometric-code - I always struggle with this.

**Comment by djzk** [comment]
Yes and no :)

There is a lot of bad spaghetti code, but I think I'll release it soon. Room stuff (server, table, etc.) and UI are made by myself, some icons are under license.

**Comment by Arcanum417** [comment]
Cmon give us something. Pls.

**Comment by Arcanum417** [comment]
No ? Ok ;(

**Comment by joshmn** [comment]
rip djzk

**Comment by djzk** [comment]
I don't work on Ruby games anymore, sorry. 

The development stopped.
